### ISSUE TITLE
Fix Send on Closed Channel

### ISSUE THREAD

**Issue by mdmarek** [lytics/grid#123]
Trace:

```
panic: send on closed channel

goroutine 279 [running]:
github.com/lytics/grid/registry.(*Registry).Watch.func2.1(0xc42028a300, 0xc42028da70)
	/Users/lulu/Code/src/github.com/lytics/grid/registry/registry.go:285 +0xf0
created by github.com/lytics/grid/registry.(*Registry).Watch.func2
	/Users/lulu/Code/src/github.com/lytics/grid/registry/registry.go:284 +0x48
exit status 2
```

**Comment by mdmarek** [comment]
Will close with #124
